/**
 * 6 Premium Themes - Professional & Creative
 * كل ثيم مصمم بعناية مع ألوان متناسقة ومتكاملة
 */

export interface ThemeColors {
  // Core colors
  background: string;
  foreground: string;
  
  // Card colors
  card: string;
  cardForeground: string;
  
  // Accent colors
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  accent: string;
  accentForeground: string;
  
  // Status colors
  destructive: string;
  destructiveForeground: string;
  success: string;
  warning: string;
  info: string;
  
  // UI Elements
  muted: string;
  mutedForeground: string;
  popover: string;
  popoverForeground: string;
  border: string;
  input: string;
  ring: string;
  
  // Chart colors (للرسوم البيانية)
  chart1: string;
  chart2: string;
  chart3: string;
  chart4: string;
  chart5: string;
}

export interface Theme {
  id: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  preview: string; // Emoji أو icon
  category: 'modern' | 'classic' | 'vibrant' | 'minimal';
  colors: {
    light: ThemeColors;
    dark: ThemeColors;
  };
}

export const PREMIUM_THEMES: Theme[] = [
  // 1. Professional - الثيم الاحترافي الكلاسيكي
  {
    id: 'professional',
    name: 'Professional',
    nameAr: 'احترافي',
    description: 'Clean and professional theme for business applications',
    descriptionAr: 'ثيم نظيف واحترافي مثالي لتطبيقات الأعمال',
    preview: '💼',
    category: 'classic',
    colors: {
      light: {
        background: '#ffffff',
        foreground: '#0a0a0a',
        card: '#ffffff',
        cardForeground: '#0a0a0a',
        primary: '#0066cc',
        primaryForeground: '#ffffff',
        secondary: '#f3f4f6',
        secondaryForeground: '#1f2937',
        accent: '#3b82f6',
        accentForeground: '#ffffff',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        warning: '#f59e0b',
        info: '#3b82f6',
        muted: '#f9fafb',
        mutedForeground: '#6b7280',
        popover: '#ffffff',
        popoverForeground: '#0a0a0a',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#0066cc',
        chart1: '#0066cc',
        chart2: '#3b82f6',
        chart3: '#60a5fa',
        chart4: '#93c5fd',
        chart5: '#dbeafe',
      },
      dark: {
        background: '#0a0a0a',
        foreground: '#fafafa',
        card: '#1a1a1a',
        cardForeground: '#fafafa',
        primary: '#3b82f6',
        primaryForeground: '#ffffff',
        secondary: '#27272a',
        secondaryForeground: '#fafafa',
        accent: '#60a5fa',
        accentForeground: '#ffffff',
        destructive: '#ef4444',
        destructiveForeground: '#ffffff',
        success: '#10b981',
        warning: '#f59e0b',
        info: '#3b82f6',
        muted: '#27272a',
        mutedForeground: '#a1a1aa',
        popover: '#1a1a1a',
        popoverForeground: '#fafafa',
        border: '#27272a',
        input: '#27272a',
        ring: '#3b82f6',
        chart1: '#3b82f6',
        chart2: '#60a5fa',
        chart3: '#93c5fd',
        chart4: '#bfdbfe',
        chart5: '#dbeafe',
      },
    },
  },

  // 2. Glassy - ثيم زجاجي شفاف عصري
  {
    id: 'glassy',
    name: 'Glassy',
    nameAr: 'زجاجي',
    description: 'Modern glassmorphism design with frosted glass effects',
    descriptionAr: 'تصميم عصري بتأثيرات زجاجية شفافة وضبابية',
    preview: '✨',
    category: 'modern',
    colors: {
      light: {
        background: '#f0f4f8',
        foreground: '#1e293b',
        card: 'rgba(255, 255, 255, 0.7)',
        cardForeground: '#1e293b',
        primary: '#8b5cf6',
        primaryForeground: '#ffffff',
        secondary: 'rgba(226, 232, 240, 0.7)',
        secondaryForeground: '#1e293b',
        accent: '#a78bfa',
        accentForeground: '#ffffff',
        destructive: '#f43f5e',
        destructiveForeground: '#ffffff',
        success: '#14b8a6',
        warning: '#fbbf24',
        info: '#06b6d4',
        muted: 'rgba(241, 245, 249, 0.8)',
        mutedForeground: '#64748b',
        popover: 'rgba(255, 255, 255, 0.9)',
        popoverForeground: '#1e293b',
        border: 'rgba(226, 232, 240, 0.5)',
        input: 'rgba(226, 232, 240, 0.5)',
        ring: '#8b5cf6',
        chart1: '#8b5cf6',
        chart2: '#a78bfa',
        chart3: '#c4b5fd',
        chart4: '#ddd6fe',
        chart5: '#ede9fe',
      },
      dark: {
        background: '#0f172a',
        foreground: '#f1f5f9',
        card: 'rgba(30, 41, 59, 0.7)',
        cardForeground: '#f1f5f9',
        primary: '#a78bfa',
        primaryForeground: '#ffffff',
        secondary: 'rgba(51, 65, 85, 0.7)',
        secondaryForeground: '#f1f5f9',
        accent: '#c4b5fd',
        accentForeground: '#1e293b',
        destructive: '#f43f5e',
        destructiveForeground: '#ffffff',
        success: '#14b8a6',
        warning: '#fbbf24',
        info: '#06b6d4',
        muted: 'rgba(30, 41, 59, 0.8)',
        mutedForeground: '#94a3b8',
        popover: 'rgba(30, 41, 59, 0.9)',
        popoverForeground: '#f1f5f9',
        border: 'rgba(51, 65, 85, 0.5)',
        input: 'rgba(51, 65, 85, 0.5)',
        ring: '#a78bfa',
        chart1: '#a78bfa',
        chart2: '#c4b5fd',
        chart3: '#ddd6fe',
        chart4: '#ede9fe',
        chart5: '#f5f3ff',
      },
    },
  },

  // 3. Dark - ثيم داكن أنيق
  {
    id: 'dark',
    name: 'Dark',
    nameAr: 'داكن',
    description: 'Elegant dark theme optimized for low-light environments',
    descriptionAr: 'ثيم داكن أنيق ومريح للعين في الإضاءة المنخفضة',
    preview: '🌙',
    category: 'modern',
    colors: {
      light: {
        background: '#1a1a2e',
        foreground: '#eaeaea',
        card: '#16213e',
        cardForeground: '#eaeaea',
        primary: '#0f3460',
        primaryForeground: '#eaeaea',
        secondary: '#533483',
        secondaryForeground: '#eaeaea',
        accent: '#e94560',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        destructiveForeground: '#ffffff',
        success: '#22c55e',
        warning: '#f59e0b',
        info: '#3b82f6',
        muted: '#0f3460',
        mutedForeground: '#94a3b8',
        popover: '#16213e',
        popoverForeground: '#eaeaea',
        border: '#0f3460',
        input: '#0f3460',
        ring: '#e94560',
        chart1: '#e94560',
        chart2: '#0f3460',
        chart3: '#533483',
        chart4: '#1a1a2e',
        chart5: '#16213e',
      },
      dark: {
        background: '#0d1117',
        foreground: '#c9d1d9',
        card: '#161b22',
        cardForeground: '#c9d1d9',
        primary: '#58a6ff',
        primaryForeground: '#ffffff',
        secondary: '#21262d',
        secondaryForeground: '#c9d1d9',
        accent: '#f78166',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        destructiveForeground: '#ffffff',
        success: '#22c55e',
        warning: '#f59e0b',
        info: '#3b82f6',
        muted: '#161b22',
        mutedForeground: '#8b949e',
        popover: '#161b22',
        popoverForeground: '#c9d1d9',
        border: '#30363d',
        input: '#0d1117',
        ring: '#58a6ff',
        chart1: '#58a6ff',
        chart2: '#f78166',
        chart3: '#79c0ff',
        chart4: '#d2a8ff',
        chart5: '#ffa657',
      },
    },
  },

  // 4. Orange Neon - ثيم نيون برتقالي جريء
  {
    id: 'orange-neon',
    name: 'Orange Neon',
    nameAr: 'نيون برتقالي',
    description: 'Bold and energetic neon orange theme that stands out',
    descriptionAr: 'ثيم برتقالي نيون جريء ومفعم بالطاقة',
    preview: '🔥',
    category: 'vibrant',
    colors: {
      light: {
        background: '#fff7ed',
        foreground: '#1c1917',
        card: '#ffffff',
        cardForeground: '#1c1917',
        primary: '#f97316',
        primaryForeground: '#ffffff',
        secondary: '#ffedd5',
        secondaryForeground: '#1c1917',
        accent: '#fb923c',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        destructiveForeground: '#ffffff',
        success: '#16a34a',
        warning: '#eab308',
        info: '#3b82f6',
        muted: '#fef3c7',
        mutedForeground: '#78716c',
        popover: '#ffffff',
        popoverForeground: '#1c1917',
        border: '#fed7aa',
        input: '#fed7aa',
        ring: '#f97316',
        chart1: '#f97316',
        chart2: '#fb923c',
        chart3: '#fdba74',
        chart4: '#fed7aa',
        chart5: '#ffedd5',
      },
      dark: {
        background: '#1c1917',
        foreground: '#fafaf9',
        card: '#292524',
        cardForeground: '#fafaf9',
        primary: '#fb923c',
        primaryForeground: '#ffffff',
        secondary: '#44403c',
        secondaryForeground: '#fafaf9',
        accent: '#fdba74',
        accentForeground: '#1c1917',
        destructive: '#dc2626',
        destructiveForeground: '#ffffff',
        success: '#16a34a',
        warning: '#eab308',
        info: '#3b82f6',
        muted: '#292524',
        mutedForeground: '#a8a29e',
        popover: '#292524',
        popoverForeground: '#fafaf9',
        border: '#44403c',
        input: '#292524',
        ring: '#fb923c',
        chart1: '#fb923c',
        chart2: '#fdba74',
        chart3: '#fed7aa',
        chart4: '#ffedd5',
        chart5: '#fff7ed',
      },
    },
  },

  // 5. Blue Sky - ثيم سماوي منعش
  {
    id: 'blue-sky',
    name: 'Blue Sky',
    nameAr: 'سماء زرقاء',
    description: 'Fresh and calming sky blue theme inspired by clear skies',
    descriptionAr: 'ثيم أزرق سماوي منعش مستوحى من السماء الصافية',
    preview: '☁️',
    category: 'minimal',
    colors: {
      light: {
        background: '#f0f9ff',
        foreground: '#0c4a6e',
        card: '#ffffff',
        cardForeground: '#0c4a6e',
        primary: '#0284c7',
        primaryForeground: '#ffffff',
        secondary: '#e0f2fe',
        secondaryForeground: '#0c4a6e',
        accent: '#38bdf8',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        destructiveForeground: '#ffffff',
        success: '#059669',
        warning: '#d97706',
        info: '#0ea5e9',
        muted: '#f0f9ff',
        mutedForeground: '#475569',
        popover: '#ffffff',
        popoverForeground: '#0c4a6e',
        border: '#bae6fd',
        input: '#e0f2fe',
        ring: '#0284c7',
        chart1: '#0284c7',
        chart2: '#0ea5e9',
        chart3: '#38bdf8',
        chart4: '#7dd3fc',
        chart5: '#bae6fd',
      },
      dark: {
        background: '#082f49',
        foreground: '#e0f2fe',
        card: '#0c4a6e',
        cardForeground: '#e0f2fe',
        primary: '#38bdf8',
        primaryForeground: '#ffffff',
        secondary: '#075985',
        secondaryForeground: '#e0f2fe',
        accent: '#7dd3fc',
        accentForeground: '#082f49',
        destructive: '#dc2626',
        destructiveForeground: '#ffffff',
        success: '#059669',
        warning: '#d97706',
        info: '#0ea5e9',
        muted: '#0c4a6e',
        mutedForeground: '#94a3b8',
        popover: '#0c4a6e',
        popoverForeground: '#e0f2fe',
        border: '#075985',
        input: '#075985',
        ring: '#38bdf8',
        chart1: '#38bdf8',
        chart2: '#7dd3fc',
        chart3: '#bae6fd',
        chart4: '#e0f2fe',
        chart5: '#f0f9ff',
      },
    },
  },

  // 6. iOS-like - ثيم مستوحى من iOS
  {
    id: 'ios-like',
    name: 'iOS-like',
    nameAr: 'آي أو إس',
    description: 'Clean and elegant design inspired by iOS interface',
    descriptionAr: 'تصميم نظيف وأنيق مستوحى من واجهة iOS',
    preview: '📱',
    category: 'minimal',
    colors: {
      light: {
        background: '#f2f2f7',
        foreground: '#000000',
        card: '#ffffff',
        cardForeground: '#000000',
        primary: '#007aff',
        primaryForeground: '#ffffff',
        secondary: '#f2f2f7',
        secondaryForeground: '#000000',
        accent: '#5ac8fa',
        accentForeground: '#ffffff',
        destructive: '#ff3b30',
        destructiveForeground: '#ffffff',
        success: '#34c759',
        warning: '#ff9500',
        info: '#5ac8fa',
        muted: '#e5e5ea',
        mutedForeground: '#3c3c43',
        popover: '#ffffff',
        popoverForeground: '#000000',
        border: '#d1d1d6',
        input: '#e5e5ea',
        ring: '#007aff',
        chart1: '#007aff',
        chart2: '#5ac8fa',
        chart3: '#34c759',
        chart4: '#ff9500',
        chart5: '#ff3b30',
      },
      dark: {
        background: '#000000',
        foreground: '#ffffff',
        card: '#1c1c1e',
        cardForeground: '#ffffff',
        primary: '#0a84ff',
        primaryForeground: '#ffffff',
        secondary: '#2c2c2e',
        secondaryForeground: '#ffffff',
        accent: '#64d2ff',
        accentForeground: '#000000',
        destructive: '#ff453a',
        destructiveForeground: '#ffffff',
        success: '#32d74b',
        warning: '#ff9f0a',
        info: '#64d2ff',
        muted: '#1c1c1e',
        mutedForeground: '#98989d',
        popover: '#1c1c1e',
        popoverForeground: '#ffffff',
        border: '#38383a',
        input: '#2c2c2e',
        ring: '#0a84ff',
        chart1: '#0a84ff',
        chart2: '#64d2ff',
        chart3: '#32d74b',
        chart4: '#ff9f0a',
        chart5: '#ff453a',
      },
    },
  },

  // 7. Emerald Garden - ثيم الحديقة الزمردية 🌿
  {
    id: 'emerald-garden',
    name: 'Emerald Garden',
    nameAr: 'الحديقة الزمردية',
    description: 'Fresh nature-inspired green theme with calm and peaceful vibes',
    descriptionAr: 'ثيم أخضر مستوحى من الطبيعة يمنح شعوراً بالهدوء والسكينة',
    preview: '🌿',
    category: 'vibrant',
    colors: {
      light: {
        background: '#f0fdf4',
        foreground: '#14532d',
        card: '#ffffff',
        cardForeground: '#14532d',
        primary: '#059669',
        primaryForeground: '#ffffff',
        secondary: '#d1fae5',
        secondaryForeground: '#14532d',
        accent: '#10b981',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        destructiveForeground: '#ffffff',
        success: '#22c55e',
        warning: '#f59e0b',
        info: '#06b6d4',
        muted: '#dcfce7',
        mutedForeground: '#166534',
        popover: '#ffffff',
        popoverForeground: '#14532d',
        border: '#86efac',
        input: '#bbf7d0',
        ring: '#059669',
        chart1: '#059669',
        chart2: '#10b981',
        chart3: '#34d399',
        chart4: '#6ee7b7',
        chart5: '#a7f3d0',
      },
      dark: {
        background: '#022c22',
        foreground: '#d1fae5',
        card: '#064e3b',
        cardForeground: '#d1fae5',
        primary: '#34d399',
        primaryForeground: '#022c22',
        secondary: '#065f46',
        secondaryForeground: '#d1fae5',
        accent: '#6ee7b7',
        accentForeground: '#022c22',
        destructive: '#f87171',
        destructiveForeground: '#ffffff',
        success: '#4ade80',
        warning: '#fbbf24',
        info: '#22d3ee',
        muted: '#064e3b',
        mutedForeground: '#a7f3d0',
        popover: '#064e3b',
        popoverForeground: '#d1fae5',
        border: '#047857',
        input: '#065f46',
        ring: '#34d399',
        chart1: '#34d399',
        chart2: '#6ee7b7',
        chart3: '#a7f3d0',
        chart4: '#d1fae5',
        chart5: '#ecfdf5',
      },
    },
  },

  // 8. Royal Purple - ثيم الأرجواني الملكي 👑
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    nameAr: 'الأرجواني الملكي',
    description: 'Luxurious and sophisticated purple theme for premium experience',
    descriptionAr: 'ثيم أرجواني فاخر ومتطور يمنح تجربة راقية',
    preview: '👑',
    category: 'classic',
    colors: {
      light: {
        background: '#faf5ff',
        foreground: '#3b0764',
        card: '#ffffff',
        cardForeground: '#3b0764',
        primary: '#7c3aed',
        primaryForeground: '#ffffff',
        secondary: '#e9d5ff',
        secondaryForeground: '#581c87',
        accent: '#a855f7',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        destructiveForeground: '#ffffff',
        success: '#16a34a',
        warning: '#f59e0b',
        info: '#6366f1',
        muted: '#f3e8ff',
        mutedForeground: '#6b21a8',
        popover: '#ffffff',
        popoverForeground: '#3b0764',
        border: '#c4b5fd',
        input: '#e9d5ff',
        ring: '#7c3aed',
        chart1: '#7c3aed',
        chart2: '#a855f7',
        chart3: '#c084fc',
        chart4: '#d8b4fe',
        chart5: '#e9d5ff',
      },
      dark: {
        background: '#1e1b4b',
        foreground: '#e0e7ff',
        card: '#312e81',
        cardForeground: '#e0e7ff',
        primary: '#a855f7',
        primaryForeground: '#ffffff',
        secondary: '#4c1d95',
        secondaryForeground: '#e0e7ff',
        accent: '#c084fc',
        accentForeground: '#1e1b4b',
        destructive: '#f87171',
        destructiveForeground: '#ffffff',
        success: '#4ade80',
        warning: '#fbbf24',
        info: '#818cf8',
        muted: '#3730a3',
        mutedForeground: '#c4b5fd',
        popover: '#312e81',
        popoverForeground: '#e0e7ff',
        border: '#4c1d95',
        input: '#3730a3',
        ring: '#a855f7',
        chart1: '#a855f7',
        chart2: '#c084fc',
        chart3: '#d8b4fe',
        chart4: '#e9d5ff',
        chart5: '#f3e8ff',
      },
    },
  },

  // 9. Sunset Bliss - ثيم غروب الشمس 🌅
  {
    id: 'sunset-bliss',
    name: 'Sunset Bliss',
    nameAr: 'غروب الشمس',
    description: 'Warm and vibrant sunset colors creating a cozy atmosphere',
    descriptionAr: 'ألوان غروب الشمس الدافئة والنابضة بالحياة تخلق أجواء مريحة',
    preview: '🌅',
    category: 'vibrant',
    colors: {
      light: {
        background: '#fff1f2',
        foreground: '#881337',
        card: '#ffffff',
        cardForeground: '#881337',
        primary: '#e11d48',
        primaryForeground: '#ffffff',
        secondary: '#ffe4e6',
        secondaryForeground: '#881337',
        accent: '#fb7185',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        destructiveForeground: '#ffffff',
        success: '#16a34a',
        warning: '#fb923c',
        info: '#f472b6',
        muted: '#fecdd3',
        mutedForeground: '#9f1239',
        popover: '#ffffff',
        popoverForeground: '#881337',
        border: '#fda4af',
        input: '#fecdd3',
        ring: '#e11d48',
        chart1: '#e11d48',
        chart2: '#f97316',
        chart3: '#fb923c',
        chart4: '#fbbf24',
        chart5: '#fcd34d',
      },
      dark: {
        background: '#450a0a',
        foreground: '#fecdd3',
        card: '#7f1d1d',
        cardForeground: '#fecdd3',
        primary: '#fb7185',
        primaryForeground: '#ffffff',
        secondary: '#991b1b',
        secondaryForeground: '#fecdd3',
        accent: '#fda4af',
        accentForeground: '#450a0a',
        destructive: '#f87171',
        destructiveForeground: '#ffffff',
        success: '#4ade80',
        warning: '#fdba74',
        info: '#f9a8d4',
        muted: '#7f1d1d',
        mutedForeground: '#fda4af',
        popover: '#7f1d1d',
        popoverForeground: '#fecdd3',
        border: '#991b1b',
        input: '#991b1b',
        ring: '#fb7185',
        chart1: '#fb7185',
        chart2: '#fb923c',
        chart3: '#fbbf24',
        chart4: '#fcd34d',
        chart5: '#fde68a',
      },
    },
  },

  // 10. Ocean Deep - ثيم أعماق المحيط 🌊
  {
    id: 'ocean-deep',
    name: 'Ocean Deep',
    nameAr: 'أعماق المحيط',
    description: 'Deep ocean blue theme with mysterious and professional feel',
    descriptionAr: 'ثيم أزرق عميق مستوحى من المحيط بطابع غامض واحترافي',
    preview: '🌊',
    category: 'modern',
    colors: {
      light: {
        background: '#ecfeff',
        foreground: '#164e63',
        card: '#ffffff',
        cardForeground: '#164e63',
        primary: '#0e7490',
        primaryForeground: '#ffffff',
        secondary: '#cffafe',
        secondaryForeground: '#164e63',
        accent: '#06b6d4',
        accentForeground: '#ffffff',
        destructive: '#dc2626',
        destructiveForeground: '#ffffff',
        success: '#14b8a6',
        warning: '#f59e0b',
        info: '#0ea5e9',
        muted: '#e0f2fe',
        mutedForeground: '#0e7490',
        popover: '#ffffff',
        popoverForeground: '#164e63',
        border: '#67e8f9',
        input: '#a5f3fc',
        ring: '#0e7490',
        chart1: '#0e7490',
        chart2: '#0891b2',
        chart3: '#06b6d4',
        chart4: '#22d3ee',
        chart5: '#67e8f9',
      },
      dark: {
        background: '#0c4a6e',
        foreground: '#e0f2fe',
        card: '#075985',
        cardForeground: '#e0f2fe',
        primary: '#22d3ee',
        primaryForeground: '#0c4a6e',
        secondary: '#0e7490',
        secondaryForeground: '#e0f2fe',
        accent: '#67e8f9',
        accentForeground: '#0c4a6e',
        destructive: '#f87171',
        destructiveForeground: '#ffffff',
        success: '#2dd4bf',
        warning: '#fbbf24',
        info: '#38bdf8',
        muted: '#164e63',
        mutedForeground: '#a5f3fc',
        popover: '#075985',
        popoverForeground: '#e0f2fe',
        border: '#0e7490',
        input: '#0e7490',
        ring: '#22d3ee',
        chart1: '#22d3ee',
        chart2: '#67e8f9',
        chart3: '#a5f3fc',
        chart4: '#cffafe',
        chart5: '#ecfeff',
      },
    },
  },
];

/**
 * Get theme by ID
 */
export function getThemeById(id: string): Theme | undefined {
  return PREMIUM_THEMES.find(theme => theme.id === id);
}

/**
 * Get all theme IDs
 */
export function getThemeIds(): string[] {
  return PREMIUM_THEMES.map(theme => theme.id);
}

/**
 * Convert theme colors to CSS variables
 */
export function themeToCSSVariables(colors: ThemeColors): Record<string, string> {
  return {
    '--background': colors.background,
    '--foreground': colors.foreground,
    '--card': colors.card,
    '--card-foreground': colors.cardForeground,
    '--primary': colors.primary,
    '--primary-foreground': colors.primaryForeground,
    '--secondary': colors.secondary,
    '--secondary-foreground': colors.secondaryForeground,
    '--accent': colors.accent,
    '--accent-foreground': colors.accentForeground,
    '--destructive': colors.destructive,
    '--destructive-foreground': colors.destructiveForeground,
    '--muted': colors.muted,
    '--muted-foreground': colors.mutedForeground,
    '--popover': colors.popover,
    '--popover-foreground': colors.popoverForeground,
    '--border': colors.border,
    '--input': colors.input,
    '--ring': colors.ring,
    '--chart-1': colors.chart1,
    '--chart-2': colors.chart2,
    '--chart-3': colors.chart3,
    '--chart-4': colors.chart4,
    '--chart-5': colors.chart5,
  };
}

export default PREMIUM_THEMES;